export const SelectTime = [
  { key: "Current Hour", value: "current-hour" },
  { key: "Last Hour", value: "last-hour" },
  { key: "Last 2 Hour", value: "last-2-hour" },
  { key: "Last 3 Hour", value: "last-3-hour" },
  { key: "Last 6 Hour", value: "last-6-hour" },
  { key: "Last 12 Hour", value: "last-12-hour" },
  { key: "Today", value: "today" },
  { key: "Yesterday", value: "yesterday" },
  { key: "This Week", value: "this-week" },
  { key: "Last Week", value: "last-week" },
  { key: "This Month", value: "this-month" },
  { key: "Last Month", value: "last-month" },
  { key: "Specific Day", value: "specific-day" },
  { key: "Between Days", value: "between-two-days" },
  { key: "Custom", value: "custom" },
];
