export const ROUTESCONSTANTS = {
  home: "/home",
  login: "/login",
  register: "/register",
  forgetPassword: "/forgot-password",
  resetPassword: "/reset-password",
  verifyResetPassToken: "/verify-reset-pass-token",
  dashboard: "/dashboard",
  // profile: "/dashboard/profile",
  editProfile: "/dashboard/profile-update",
  updatePassword: "/dashboard/password-update",

  reports: "/reports",
  tracking: "/tracking",
  operation: "/operation",
  admin: "/admin",
  profile: "/profile",
  accounting: "/accounting",
  serviceCharge: "/service-charge",
};
